### ISSUE TITLE
Zlepšení indikace stavů přístrojů před startem

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/mavlink-websocket#6]
Při posledních letových testech se ukazuje dosavadní přístup k indikátorům jako nedostatečný a je zřejmě potřeba jej zlepšit. 
Důsledkem aktuální nedostatečnosti jsou tyto potíže:

- [ ] [Řidič netuší, jakou rychlostí má při startu jet](https://github.com/ThunderFly-aerospace/TF-G2/issues/62).
- [ ] [Není jasné v jakém stavu se nachází vírník a platforma](https://github.com/ThunderFly-aerospace/TF-SIMPLEPLATFORM/issues/10)
- [ ] [Dlouho trvá, než operátor rozpozná výpadek spojení](https://github.com/ThunderFly-aerospace/WebDashboard/issues/1)

Jako dobrý vzor mi přijde přístup, který používají ve [SpaceX pro crew dragon](https://os-system.com/blog/javascript-in-space-spacex-devs-have-shared-crewdragons-tech-stack/). Shrnutí základních poznatků je v [tomhle videu](https://www.youtube.com/watch?v=J5VECXgTpWk).  

Jeden ze základních poznatků je, že oni považují grafickou kvalitu za základní stavební kamen všech grafických prvků. Neboť to zaručuje přehlednost. 
Druhým významným poznatkem, který nevím jestli je pro nás akceptovatelný je, že si všechny javascriptové knihovny píšou sami, aby měli kontrolu nad kódem a závislostmi. 

Mě na jejich grafice zaujalo to, že se naopak nesnaží napodobovat dosavadní grafické indikátory používané v aerospace. Místo toho naopak používají intuitivní barevnou grafiku s obrázky a jednoduchými modely. Nevím však zda máme na terminálech dostatečný výpočetní výkon, abychom si něco takového mohli dovolit.
